spring:
   profiles:
   active:
   - dev
---
server:
  port: 8080
  
spring:
  profiles: dev
  application:
    name: servicecloud-dept
  datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: org.gjt.mm.mysql.Driver
       url: jdbc:mysql://localhost:3306/coulddb0001
       username: root
       password: 123456
       dbcp2:
         min-idle: 5
         initial-size: 5
         max-total: 5
         max-wait-millis: 200
         
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.njau.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: servicecloud-dept8001
    prefer-ip-address: true   #访问路径显

info:
   app.name: njau-servicecloud
   company_name: www.njau.com
   build.artifactId: $project.artifactId$    
   bulid.version: $project.version$    